include ../Makefile

LIBS=core
include ../lib.mk
PORT=/dev/ttyACM1

Blink.elf: libcore.a

# compile project:
# make Blink.elf

# programm board:
# make Blink.prog

# monitor board:
# make monitur

# Cleanup
# make clean
